version: '3'
services:
  backend:
    build: LyricDb.Web
    depends_on:
      - worker
    networks:
      - backend
  worker:
    build: LyricDb.Worker
  frontend:
    build: LyricDb.Frontend
    depends_on:
      - backend
networks:
  backend: 
    
  frontend:
