version: '3'
services:
  backend:
    image: ghcr.nju.edu.cn/kengwang/lyricdb-backend:latest
    ports:
      - "17630:5140"
    depends_on:
      - worker
    networks:
      - backend
    environment:
      - ConnectionStrings__Postgres=Host=1Panel-postgresql-Br8o;Port=5432;Database=lyricdb;Username=user_DETQwf;Password=password_kfecPz"
      - Wolverine__Web=17757
      - Wolverine__Worker=17758
  worker:
    image: ghcr.nju.edu.cn/kengwang/lyricdb-worker:latest
    networks:
      - backend
    environment:
      - Wolverine__Web=17757
      - Wolverine__Worker=17758
  frontend:
    image: ghcr.nju.edu.cn/kengwang/lyricdb-frontend:latest
    depends_on:
      - backend
    ports:
      - "17631:3000"
networks:
  backend:
  
  frontend: