name: Docker Image Build
on:
  push: 
    branches:
      - main
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kengwang --password-stdin
      - name: Build and push
        run: |
          cd LyricDb.Backend
          docker build . -t ghcr.io/kengwang/lyricdb-backend:latest --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/kengwang/lyricdb-backend:$(date +%s)